SELECT USER_ID, NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
LEFT JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = "DONE"
GROUP BY USER_ID,NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES