SELECT FLAVOR
    FROM (
            SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
            UNION ALL
            SELECT FLAVOR, TOTAL_ORDER FROM JULY
         ) BASE
    GROUP BY FLAVOR     
    ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3

# another solution
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN JULY J
    ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY (F.TOTAL_ORDER + SUM(J.TOTAL_ORDER)) DESC
LIMIT 3